### ISSUE TITLE
Missing CSS?

### ISSUE THREAD

**Issue by mlincoln** [CIDI/kennethware-2.0#2]
Hi,
I followed the instructions to install this on my test instance, and I can now launch the tools from the editor.
I tried creating some tabs, and they don't appear to render for me when I save and view the page.
When I right-click and inspect where the tabs should be, I see a number of classes that don't appear in my stylesheet.
kl_tab_content is one. Is there additional styling I am missing?

**Comment by duniken** [comment]
Sorry, I am relatively new to GitHub and the code was created under a department account so I did not get a notification about this issue. I would recommend updating to the newest version of the code (after I update again today) and let me know if this is still causing issues.
