### ISSUE TITLE
Iframe conflict in the template editor

### ISSUE THREAD

**Issue by melignus** [CIDI/kennethware-2.0#33]
Iframe selector in the editor can give you a CORS error if you have other external_tools loaded that have iframes.

https://github.com/CIDI/kennethware-2.0/blob/bba58d6932eb85ac54e688a256cb01f298e6a6a4/js/master_controls.js#L137

`$('iframe').contents()`

Causes the error if an iframe on the page is loaded from a different origin. In our case we had another external_tool that loaded up a chat module into an iframe on the course->page->editor page that prevented the rest of the tool from loading.

**Comment by duniken** [comment]
Merged in your fix for this. Thanks for contributing!
