### ISSUE TITLE
Image uploader throws non-critical errors

### ISSUE THREAD

**Issue by melignus** [CIDI/kennethware-2.0#34]
https://github.com/CIDI/kennethware-2.0/blob/bba58d6932eb85ac54e688a256cb01f298e6a6a4/wizard/resources/wizard_image_crop.php#L413-L416

$uploadData is never defined.

**Comment by melignus** [comment]
This fixes the issue posted in #32 btw.

**Comment by duniken** [comment]
Merged your fix, thanks.
