### ISSUE TITLE
Script loading/execution order impacting tool loading

### ISSUE THREAD

**Issue by IUeDS-User** [CIDI/kennethware-2.0#5]
Noticed this after merging the latest upstream changes into our fork...It seems that on some page loads, the scripts may execute in a different order, causing the Live View/Edit Tools to function sometimes, sometimes not. Here is the console output from a few page loads, both View and Edit modes, the logged output is slightly different between them:

On page view:

Working (additional_customization.js loads early)
![view-console-output-working](https://cloud.githubusercontent.com/assets/8459672/5667206/f6a9e780-9733-11e4-9693-ef88dac0f8a5.jpg)

Not working
![view-console-output-not-working](https://cloud.githubusercontent.com/assets/8459672/5667205/f6a6b178-9733-11e4-84e3-4b8e9b34161c.jpeg)

On Edit view:

Working (additional_customization.js loads early)
![edit-console-output-working](https://cloud.githubusercontent.com/assets/8459672/5667207/f6aab5de-9733-11e4-9670-f90fac714507.jpeg)

Not working ("Launch Tools" blue button does not appear)
![edit-console-output-not-working](https://cloud.githubusercontent.com/assets/8459672/5667244/396e2e46-9734-11e4-83e5-7d9383a74f41.jpg)

I've seen this in Mac Chrome Version 39.0.2171.95 (64-bit). Are you experiencing sporadic loading of the Tools in view and edit modes?

**Comment by duniken** [comment]
I believe I have this issue fixed, I am doing some final testing and should have this one updated by the end of the day today

**Comment by duniken** [comment]
I have uploaded the fixed code. Let me know if you there are any other issues. Thanks!
